CREATE DATABASE JOINS;
USE JOINS;
CREATE TABLE STUDENT(ID INT PRIMARY KEY ,NAME VARCHAR(50));
INSERT INTO STUDENT(ID,NAME)
VALUES
(101,"ADAM"),
(102,"BOB"),
(103,"CASEY");
CREATE TABLE COURSE(STUDENT_ID INT PRIMARY KEY,COURSE VARCHAR(20));
INSERT INTO COURSE(STUDENT_ID,COURSE)
VALUES
(102,"ENGLISH"),
(105,"MATH"),
(103,"SCIENCE"),
(107,"COMPUTER SCIENCE");
