create database collage;
use collage;

insert into MY_SCHOOL(roll_no,name,marks,grade,city)
values
(101,"anil",78,"c","pune"),
(102,"bhumika",93,"a","mumbai"),
(103,"chetan",85,"b","mumbai"),
(104,"dhruv",96,"a","delhi"),
(105,"riya",12,"f","delhi"),
(106,"farah",82,"b","delhi");
show databases;
select*from student;
select city from student;
select distinct city from student;
select name from student where marks>80;
select*from student where marks>80;
SELECT NAME, MARKS FROM STUDENT WHERE MARKS>80;
SELECT*FROM STUDENT WHERE MARKS>80 AND CITY= "MUMBAI";
SELECT*FROM STUDENT WHERE MARKS+10>100;
SELECT*FROM STUDENT WHERE MARKS<75 OR CITY="MUMBAI";
SELECT*FROM STUDENT WHERE MARKS BETWEEN 75 AND 90;
SELECT*FROM STUDENT WHERE CITY IN("DELHI","MUMBAI");
SELECT*FROM STUDENT WHERE CITY NOT IN ("DELHI","MUMBAI");
SELECT*FROM STUDENT WHERE CITY != "DELHI"AND"MUMBAI";
SELECT*FROM STUDENT WHERE MARKS>=75 LIMIT 3;
SELECT*FROM STUDENT LIMIT 3 OFFSET 2;
SELECT NAME, ROLL_NO FROM STUDENT WHERE GRADE = "a";
select*from student order by marks desc;
SELECT*FROM STUDENT ORDER BY MARKS ASC;
SELECT*FROM STUDENT ORDER BY MARKS;
SELECT*FROM STUDENT ORDER BY MARKS DESC LIMIT 3;
SELECT*FROM STUDENT ORDER BY MARKS DESC LIMIT 3 OFFSET 1;
SELECT*FROM STUDENT ORDER BY MARKS DESC LIMIT 3 OFFSET 0;
#AGGREGATE FUNCTIONS
SELECT MAX(MARKS) FROM STUDENT;
SELECT MIN(MARKS) FROM STUDENT;
SELECT SUM(MARKS) FROM STUDENT;
SELECT AVG(MARKS) FROM STUDENT;
SELECT COUNT(MARKS) FROM STUDENT;
SELECT COUNT(NAME) FROM STUDENT;
SELECT CITY, COUNT(ROLL_NO) FROM STUDENT GROUP BY CITY;
SELECT CITY ,AVG(MARKS) FROM STUDENT GROUP BY CITY;
SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY CITY ORDER BY CITY DESC ;
SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY CITY ORDER BY AVG(MARKS) DESC ;
select max(marks) from student;
select min(marks) from student;
SELECT NAME,CITY FROM STUDENT;
SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY CITY ORDER BY AVG(MARKS) ASC;
SELECT *FROM STUDENT;
SELECT*FROM STUDENT WHERE GRADE="A" AND CITY="DELHI";
SELECT*FROM STUDENT ORDER BY MARKS DESC;
SELECT*FROM STUDENT ORDER BY CITY ASC;
SELECT*FROM STUDENT ORDER BY CITY DESC;
SELECT*FROM STUDENT ORDER BY NAME ASC;
SELECT*FROM STUDENT ORDER BY NAME DESC;
SELECT MAX(MARKS) FROM STUDENT;
SELECT MIN(MARKS)FROM STUDENT;
SELECT NAME,MARKS FROM STUDENT ORDER BY MARKS DESC LIMIT 3;
SELECT NAME,MARKS,CITY FROM STUDENT ORDER BY CITY DESC LIMIT 5 OFFSET 0;
SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY CITY ORDER BY AVG(MARKS) ASC;
SELECT CITY,COUNT(ROLL_NO) FROM STUDENT GROUP BY CITY HAVING(MAX(MARKS)>90); 
SELECT CITY FROM STUDENT WHERE GRADE="A" GROUP BY CITY HAVING MAX(MARKS)>90 ORDER BY CITY;     
# UPDATE FUNCTION IN SQL
SET SQL_SAFE_UPDATES=0;
UPDATE STUDENT SET ROLL_NO =107 WHERE ROLL_NO =102;  
UPDATE STUDENT SET MARKS = MARKS+ 1 ;
# DELETE FUNCTION       
DELETE FROM STUDENT WHERE MARKS<30;
#ADD COLUMN YAHA SE TABLE NAME CHANGE HO GAYA THA AFTER TRANCATE USE KRNE KE BAAD
ALTER TABLE MY_SCHOOL ADD COLUMN AGE INT NOT NULL DEFAULT 19;
#MODIFY TABLE COLUMN
ALTER TABLE MY_SCHOOL MODIFY AGE  VARCHAR (2);
INSERT INTO MY_SCHOOL (ROLL_NO,NAME,MARKS,GRADE,CITY,AGE)
VALUES(109,"RAJ",83,"B","PUNE",10);
#CHANGE COLUMN NAME AND DATATYPE IN TABLE
ALTER TABLE MY_SCHOOL CHANGE COLUMN AGE STUD_AGE INT;
#DROP COLUMN
ALTER TABLE MY_SCHOOL DROP COLUMN STUD_AGE;
#RENAME TABLE
ALTER TABLE MY_SCHOOL RENAME MY_SCHOOL;
# TRANCATE FUNCTION FOR DELETE ALL VALUES FROM TABLE
TRUNCATE TABLE MY_SCHOOL;
# QUERY
DELETE FROM MY_SCHOOL WHERE MARKS <30;
                      











